### PR TITLE
Rewrite the README, setting out more clear project goals.

### PR DESCRIPTION
**Pull request by dabreegster**
See the [rendered docs here](https://github.com/a-b-street/osm2streets/blob/docs/README.md). To get a better sense of what osm2streets is about, go to https://a-b-street.github.io/osm2streets/?test=st_georges_cycletrack, enable all 3 of the settings, hit **reimport**, then towards the bottom, repeatedly press **next** to see the magic in action, step by step.

The goal for this README is to be pretty self-contained, but if you're really confused, you can also peek at the [slides](https://dabreegster.github.io/talks/sotm_2022/slides.html) for my State of the Map talk in a few days.

I'm interested in getting feedback from a wide variety of people who could possibly build off of or join this project. Any kind of feedback is welcome -- including "I have no idea what's going on" and "this is a terrible idea because X".

@BudgieInWA and @droogmic: y'all've been building this too, so hopefully nothing here is too much of a surprise. Any feedback welcome!

@Robinlovelace, @GretaTimaite, @hulsiejames: from an openinfra perspective, I hope this library can help tackle some of the low-level work. It's hard to answer if a road has a cycletrack or a sidewalk when they're tagged as parallel ways in OSM, or to figure out the type of segregation. Or to figure out the total right-of-way width available in some road to see if it could support cycle lanes. We're trying to solve those hard problems here. Maybe openinfra data packs can run osm2streets on whatever areas different LAs need and use the library to answer questions like this.

@darribas: here's a more detailed explanation of the proposals I've been making. :)  I see osm2streets as a "foundational" library that other urban analytics projects could build upon if they need to analyze data at the street level.

@matkoniecz: It's been a while! Lots of the issues we discussed long ago in A/B Street are now making actual progress here, and we have a "unit test"-like setup and a way to interactively debug that's helping us along. I want to build some web apps on top of osm2streets to make lane tagging in OSM super easy.

@kfarr: I haven't been following 3D Street much, but if you recall the GeoJSON files of intersection/road areas I sent a while back, now you can generate those and more yourself through regular JS. Check out the geojson layer downloads in the tool and I can point you towards some code for how the JS API works.

@martinfleis: We've now got some transformations half-working here that handle pretty complex situations with some types of dual carriageways and parallel roads. If there's any way this project can be helpful to the GSoC project, let me know. And I'm following progress there closely -- if y'all figure out any algorithms to handle certain situations, I'd love to implement them here too. Note the focus of this project is on OSM, but if you swap out the `import_streets` crate in the architecture diagram with some other source, then there's nothing stopping you from using the rest of this project to deal with other data sources.

@mvl22: After your explanation at MW, I'm still not convinced consolidating parallel ways into a single object with a list of lanes is a good idea in all cases. I've found a few complex ones around London where it seems to be a pretty good representation, though. The transformations in osm2streets are configurable / you can opt into what you want. If any of what we're doing would be useful for CycleStreets, let me know.

### CODE REVIEW

**Comment by martinfleis** [comment]
cc @gregmaya @gsagostini

**Comment by dabreegster** [comment]
Somehow I forgot @tordans from my list, sorry! Another way to phrase the goal of this project is to replicate the magic of Straßenraumkarte more widely and make the data easier to work with. I'll open some new issues soon to discuss specifics...

**Comment by Robinlovelace** [comment]
> Maybe openinfra data packs can run osm2streets on whatever areas different LAs need and use the library to answer questions like this.

Agreed, it would be great if the data packs could contain versions of the OSM data that have been processed by osm2streets. One comment about language: the word 'simplified' comes up. Am I right in thinking that the *tags* are simplified while the geometry is 'complexified' and 'blown-up'? My understanding is that `osm2streets` usefully creates many new vertices and linestrings representing roads while OSM typically only renders the centreline.

**Comment by dabreegster** [comment]
> Am I right in thinking that the tags are simplified while the geometry is 'complexified' and 'blown-up'?

For openinfra or other consumers that need information about the lanes on the road, the idea is that they wouldn't touch the OSM tags at all. They would read a list of lanes left-to-right with a (type, width, direction). (For now, more detail possible later.) If you wanted to know if a road has an LTN120 compliant cycle lane on one side, you could check the width and see if there's a buffer/separator on the left or right side of the lane. We will probably have helper functions like this to ask high-level questions about the lanes, and can also expose those through the API.

So we aren't simplifying the OSM tags. We're transforming them into something much easier to understand.

> My understanding is that osm2streets usefully creates many new vertices and linestrings representing roads while OSM typically only renders the centreline.

Yes, we make the geometry "more complex" in that sense. It's exposed through different GeoJSON layers, with properties labelling things. So if you just wanted the OSM center-lines, you could still ask osm2streets for that layer. But if you want to render the library's understanding of physical space, you can do that too. Or if you also want the lane markings (dashed lines, turn arrows, etc), those will be there too, and improved over time.

**Comment by dabreegster** [comment]
I'm going to merge this, so anyone finding the repo before SotM is less confused. But I still welcome asynchronous feedback on this PR, in issues, or elsewhere. Thanks!

**Comment by fhk** [comment]
I've started some research on capabilities and found this - https://sdna-open.readthedocs.io/en/latest/step_by_step_guides.html#modelling-a-combined-vehicle-and-cycle-network

There is also a open source fork of sdna 

More to come...

**Pull request merged**
